spring:
  profiles: default
  application:
    name: restful-blog
eureka:
  instance:
#    appGroupName: null
#    nonSecurePortEnabled: true
#    statusPageUrl: null
#    initialStatus: "UP
#    instanceEnabledOnit: false
#    homePageUrl: null
#    securePort: 443
#    securePortEnabled: false
#    healthCheckUrlPath: "/health"
#    leaseExpirationDurationInSeconds: 1
#    metadataMap: {}
#    preferIpAddress: false
#    healthCheckUrl: null
    statusPageUrlPath: "/info"
#    virtualHostName: "eureka-server
#    ipAddress: "192.168.214.1
#    leaseRenewalIntervalInSeconds: 5
#    homePageUrlPath: "/
#    nonSecurePort: 9002
#    namespace: "eureka
#    secureVirtualHostName: null
#    secureHealthCheckUrl: null
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/
---
spring:
  profiles: server1
server:
  port: 9004
---
spring:
  profiles: server2
server:
  port: 9005
---
spring:
  profiles: server3
server:
  port: 9006